AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Workflow for Processing SNS Messages

Globals:
  Function:
    Runtime: python3.11
    MemorySize: 512
    Timeout: 120

Parameters:
  ProjectName:
    Type: String
    Default: cloud-works
    Description: Name of the project
  StackName:
    Type: String
    Description: Name of the stack
  ExecEnv:
    Type: String
    Description: Execution environment
    AllowedValues:
      - dev
      - staging
      - prod
  RegionName:
    Type: String
    Default: us-east-1

Mappings:
  Layers:
    cloud-works-common-layer:
      ApplicationId: 'arn:aws:serverlessrepo:${AWS::Region}:${AWS::AccountId}:applications/workflow-common-layer'
    cloud-works-pg-layer:
      ApplicationId: 'arn:aws:serverlessrepo:${AWS::Region}:${AWS::AccountId}:applications/workflow-pg-layer'

Resources:

  #  Layers with dependencies
  CommonLayer:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: !FindInMap [ Layers, cloud-works-common-layer, ApplicationId ]
        SemanticVersion: '1.0.7'
      Parameters:
        ProjectName: !Ref ProjectName
        StackName: !Ref StackName
        ExecEnv: !Ref ExecEnv

  PgLayer:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: !FindInMap [ Layers, cloud-works-pg-layer, ApplicationId ]
        SemanticVersion: '1.0.0'
      Parameters:
        ProjectName: !Ref ProjectName
        StackName: !Ref StackName
        ExecEnv: !Ref ExecEnv

  # IAM Role for PublishMessages Lambda
  PublishMessagesFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
            Condition:
              StringEquals:
                aws:SourceAccount: "${AWS::AccountId}"
      Description: 'Role definition for PublishMessagesFunction'
      Policies:
        - PolicyName: !Sub '${ProjectName}-${StackName}-pm-policy-${ExecEnv}'
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'sns:Publish'
                Resource: !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:process-messages-topic'
              - Effect: Allow
                Action:
                  - 'secretsmanager:GetSecretValue'
                Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:msg-topic-arn-${ExecEnv}-*'


  # IAM Role for ProcessMessages Lambda
  ProcessMessagesFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
            Condition:
              StringEquals:
                aws:SourceAccount: "${AWS::AccountId}"
      Description: 'Role definition for ProcessMessagesFunction'
      Policies:
        - PolicyName: !Sub '${ProjectName}-${StackName}-pr-policy-${ExecEnv}'
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'sqs:ReceiveMessage'
                  - 'sqs:DeleteMessage'
                  - 'sqs:GetQueueAttributes'
                Resource:
                  - !Sub 'arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:alerts-queue'
                  - !Sub 'arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:notifications-queue'
              - Effect: Allow
                Action:
                  - 'secretsmanager:GetSecretValue'
                Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:msg-db-credentials-${ExecEnv}-*'

  # Lambda for publishing messages on SNS
  PublishMessagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-${StackName}-publish-messages-${ExecEnv}'
      Layers:
        - !GetAtt CommonLayer.Outputs.LambdaLayerArn
      CodeUri: lambdas/fPublishMessages/src/
      Handler: app.lambda_handler
      Role: !GetAtt PublishMessagesFunctionRole.Arn
      Environment:
        Variables:
          MSG_TOPIC_ARN_SECRET_NAME: !Sub 'msg-topic-arn-${ExecEnv}'

  # Lambda for processing SQS Messages
  ProcessMessagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-${StackName}-process-messages-${ExecEnv}'
      Layers:
        - !GetAtt CommonLayer.Outputs.LambdaLayerArn
        - !GetAtt PgLayer.Outputs.LambdaLayerArn
      CodeUri: lambdas/fProcessMessages/src/
      Handler: app.lambda_handler
      Role: !GetAtt ProcessMessagesFunctionRole.Arn
      Environment:
        Variables:
          MSG_DB_SECRET_NAME: !Sub 'msg-db-credentials-${ExecEnv}'

  NotificationsEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 10
      EventSourceArn: !Sub 'arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:notifications-queue'
      FunctionName: !GetAtt ProcessMessagesFunction.Arn
      Enabled: "true"

  AllowNotificationsQToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ProcessMessagesFunction
      Principal: sqs.amazonaws.com
      SourceArn: !Sub 'arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:notifications-queue'

  AlertsEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 10
      EventSourceArn: !Sub 'arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:alerts-queue'
      FunctionName: !GetAtt ProcessMessagesFunction.Arn
      Enabled: "true"

  AllowAlertsQToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ProcessMessagesFunction
      Principal: sqs.amazonaws.com
      SourceArn: !Sub 'arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:alerts-queue'

  ProcessMessagesStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionSubstitutions:
        PublishMessagesFunctionArn: !GetAtt PublishMessagesFunction.Arn
        ProcessMessagesFunctionArn: !GetAtt ProcessMessagesFunction.Arn
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref PublishMessagesFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref ProcessMessagesFunction
      DefinitionUri: stacks/process-messages-workflow/statemachine/process_messages.asl.json
